config:
  info: this is a test config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://test.eureka7001.com:7001/eureka, http://test.eureka7002.com:7002/eureka