config:
  info: this is a prod config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://prod.eureka7001.com:7001/eureka, http://prod.eureka7002.com:7002/eureka